default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # This must match what POSTGRES_USER was set to in docker-compose.yml.
  username: zero_api
  # This must be 127.0.0.1 and not localhost.
  host: 127.0.0.1

development:
  <<: *default
  database: zero_api_development

test:
  <<: *default
  database: zero_api_test

production:
  <<: *default
  database: zero_api_production
  # username: zero_api
  # password: <%= ENV['DB_PASSWORD'] %>
